version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    volumes:
      - /usr/src/koneurakointi/flask_app/static
    ports:
      - "5000:5000"
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app
