version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    expose:
      - "5000"
    volumes:
      - /root/koneurakointi/flask_app/static
    command: gunicorn --workers=1 --bind :5000 wsgi:app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
    depends_on:
      - flask_app
